import React from 'react';
import { Download, FileText, CheckCircle2 } from 'lucide-react';
import { ReportItem } from '../../types';

interface PDFReportExporterProps {
  report: ReportItem;
  className?: string;
}

export const PDFReportExporter: React.FC<PDFReportExporterProps> = ({ report, className = '' }) => {
  const [downloading, setDownloading] = React.useState(false);
  const [downloaded, setDownloaded] = React.useState(false);

  const handleDownloadPDF = () => {
    setDownloading(true);

    // Create a print window / blob structure formatted cleanly as PDF document HTML
    const pdfContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${report.title} - Black Swan Financial Risk Intelligence</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #0F172A; margin: 40px; background: #FFF; }
          .header { border-bottom: 2px solid #0F172A; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end; }
          .brand { font-size: 24px; font-weight: 800; color: #1E293B; letter-spacing: -0.5px; }
          .tag { font-size: 11px; font-weight: 700; text-transform: uppercase; background: #EF4444; color: #FFF; padding: 4px 10px; border-radius: 99px; }
          .title { font-size: 28px; font-weight: 800; margin-bottom: 12px; color: #0F172A; line-height: 1.2; }
          .meta { font-size: 13px; color: #64748B; margin-bottom: 24px; }
          .summary-box { background: #F8FAFC; border-left: 4px solid #3B82F6; padding: 16px; margin-bottom: 30px; font-size: 14px; line-height: 1.6; color: #334155; }
          .section { margin-bottom: 28px; }
          .section-title { font-size: 18px; font-weight: 700; border-bottom: 1px solid #E2E8F0; padding-bottom: 6px; margin-bottom: 12px; color: #1E293B; }
          .section-body { font-size: 14px; line-height: 1.6; color: #334155; white-space: pre-line; }
          .footer { border-top: 1px solid #E2E8F0; padding-top: 16px; margin-top: 40px; font-size: 11px; color: #94A3B8; text-align: center; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="brand">∆ BLACK SWAN INTEL</div>
            <div style="font-size: 12px; color: #64748B; margin-top: 4px;">Global Financial Risk Intelligence Platform</div>
          </div>
          <div class="tag">${report.severityTag.toUpperCase()} SEVERITY</div>
        </div>

        <div class="title">${report.title}</div>
        <div class="meta">Published: ${report.createdAt} | Author: ${report.author}</div>

        <div class="summary-box">
          <strong>Executive Summary:</strong><br/>
          ${report.summary}
        </div>

        ${report.sections.map(sec => `
          <div class="section">
            <div class="section-title">${sec.heading}</div>
            <div class="section-body">${sec.body}</div>
          </div>
        `).join('')}

        <div class="footer">
          CONFIDENTIAL - PROPRIETARY FINANCIAL RISK INTELLIGENCE REPORT - GENERATED BY BLACK SWAN PLATFORM
        </div>
      </body>
      </html>
    `;

    setTimeout(() => {
      const blob = new Blob([pdfContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);

      // Open print prompt or anchor download
      const printWindow = window.open(url, '_blank');
      if (printWindow) {
        printWindow.onload = () => {
          printWindow.print();
        };
      }

      setDownloading(false);
      setDownloaded(true);
      setTimeout(() => setDownloaded(false), 3000);
    }, 600);
  };

  return (
    <button
      onClick={handleDownloadPDF}
      disabled={downloading}
      className={`inline-flex items-center gap-2 px-4 py-2 rounded-lg font-semibold text-sm transition-all shadow-md ${
        downloaded
          ? 'bg-emerald-600 text-white'
          : 'bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white'
      } ${className}`}
    >
      {downloading ? (
        <>
          <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
          Generating PDF...
        </>
      ) : downloaded ? (
        <>
          <CheckCircle2 className="w-4 h-4" />
          PDF Generated
        </>
      ) : (
        <>
          <Download className="w-4 h-4" />
          Download PDF Report
        </>
      )}
    </button>
  );
};
